### PR TITLE
esm: rename service description

### PR DESCRIPTION
**Pull request by lucasmoura**
## Proposed Commit Message
esm: rename service description

Update description of esm-infra and esm-apps

## Test Steps
Verify if the integration tests are still working as expected

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by orndorffgrant** [comment]
looks good, but needs some conflicts resolved after the latest merge. Also the integration tests didn't run for some reason - hopefully they'll run on the next push

**Review by orndorffgrant — APPROVED** [review]

**Comment by renanrodrigo** [comment]
I see some entries of ROS ESM here still read as Extended - should those be changed to Expanded as well?

**Comment by renanrodrigo** [comment]
Messed up but fixed it in time :|

**Comment by lucasmoura** [comment]
@renanrodrigo ROS service updated

**Review by renanrodrigo — APPROVED** [review]

**Pull request merged**
