### PR TITLE
sru: add test instructions to unattached status job (SC-599)

### PR DESCRIPTION
**Pull request by renanrodrigo**
As posted in [the related LP bug](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1950813)

## Desired commit type
 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by orndorffgrant — APPROVED** [review]
:+1: I also scriptified this and uploaded test results to https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1950813

**Comment by renanrodrigo** [comment]
@orndorffgrant just saw the script
I think it would make more sense not merging this then, and keeping the scripted version in the SRU folder. What do you think?

**Comment by orndorffgrant** [comment]
@renanrodrigo True that makes sense to me

**Comment by renanrodrigo** [comment]
@orndorffgrant now it has your script
Looks good to me haha

**Review by blackboxsw — APPROVED** [review]
Test script looks good. And Grant's capture of output there in the bug.

**Pull request merged**
