### PR TITLE
Allow running tests with ephemeral instances (SC-266)

### PR DESCRIPTION
**Pull request by lucasmoura**
## Proposed Commit Message
Allow running tests with ephemeral instances

We are now allowing running the integration tests with ephemeral instances. This will allow LXD to better handle deleting the instance, since we can now just stop the ephemeral instance and LXD will properly handle the deletion of the instance

## Test Steps
Run any integration test with `UACLIENT_BEHAVE_EPHEMERAL_INSTANCE=1` and verify that the instance created instance
is an ephemeral one

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by paride — COMMENTED** [review]
I tested this and it works fine, thanks! One thing: I noticed that the `ubuntu-behave-image-build-*` container is not created ephemeral. Should we also move it to ephemeral when the env variable is set? Or was your idea to leave it as it is for the moment as we're switching to schroot based builds?

**Comment by lucasmoura** [comment]
@paride the reason why the `image-build` instances are not ephemeral is because we create snapshots from them. To create a snapshot on [pycloudlib](https://github.com/canonical/pycloudlib/blob/main/pycloudlib/lxd/instance.py#L374) when shutdown the instance, which will not work if is ephemeral.

Also, this will not change if we have the build package stage running on chroot, because those `image-build` instances are the ones that we install the built packages. We snapshot this image to speed up the running all of the tests that requires the latest version of ua

**Comment by paride** [comment]
Thanks @lucasmoura for explaining. About the snapshotting I filed: https://github.com/canonical/pycloudlib/issues/159. Should that indeed work we could expand this PR to also cover the build containers, and go fully ephemeral.

**Review by paride — APPROVED** [review]
LGTM and ready to be merged per standup discussion.

**Pull request merged**
