### PR TITLE
tests: update curl versions in package list test

### PR DESCRIPTION
**Pull request by orndorffgrant**
CI should pass for these tests again

### CODE REVIEW

**Comment by renanrodrigo** [comment]
oh no, again...
we gotta find a better way to test this :/

**Comment by renanrodrigo** [comment]
seems to be failing for Kinetic - yet another reason to find a better way to test...

**Comment by orndorffgrant** [comment]
Maybe a slow mirror sync, I'll re-run the failed job

**Comment by renanrodrigo** [comment]
No I've actually seen this in the past - this test passing locally and failing on CI (or vice versa) due to different versions...

**Review by renanrodrigo — APPROVED** [review]
-1
unapproved
we need a different approach, using apt policy as @lucasmoura suggested

**Pull request merged**
