### PR TITLE
messaging: correct num covered packages

### PR DESCRIPTION
**Pull request by orndorffgrant**
## Test Steps

Integration tests should still pass

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by renanrodrigo** [comment]
seems there is a conflict already hehe

**Comment by orndorffgrant** [comment]
ugh I guess I didn't fetch, fixing...

**Comment by orndorffgrant** [comment]
updated

**Review by lucasmoura — APPROVED** [review]

**Comment by renanrodrigo** [comment]
hhhmmm I see you merged this to `main`
I'll open a PR bringing it to `release-27`

**Pull request merged**
