### PR TITLE
Hirsute no more

### PR DESCRIPTION
**Pull request by renanrodrigo**
As Hirsute is EOL, this updates the readme and the test suite.

## Test Steps
Maybe run the changed tests, just to be sure

## Desired commit type
 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist
 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [x] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by CalvoM** [comment]
Lgtm, I think the only parts with hirsuite are in the go tests.

**Comment by renanrodrigo** [comment]
@CalvoM true: I didn't remove them because they are just mocks. Can do if anyone thinks it is relevant to (:

**Comment by lucasmoura** [comment]
I agree with @CalvoM on removing that from the go hooks as well.

**Comment by renanrodrigo** [comment]
@CalvoM @lucasmoura done

**Review by lucasmoura — APPROVED** [review]
LGTM to me.
Marking @orndorffgrant because changes were made on the go hooks

**Comment by orndorffgrant** [comment]
Cool thanks for this. I'll just run some of the more interesting changed tests plus the go hook tests before approving

**Review by orndorffgrant — APPROVED** [review]
Everything worked for me! Merging

**Pull request merged**
