### PR TITLE
dev-doc: add guide to permanently detach Pro instances (SC-1214)

### PR DESCRIPTION
**Pull request by aciba90**
## Proposed Commit Message

```
dev-doc: add guide to permanently detach Pro instances

Fixes: #2177
```

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [x] I have updated or added any documentation accordingly

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by lucasmoura** [comment]
I am just wondering if this should on our public docs instead. What do you think @orndorffgrant @renanrodrigo @CalvoM ?

**Comment by renanrodrigo** [comment]
I think it should be dev-docs, because it is a workaround for internal uses, but I can be convinced either way

**Comment by s-makin** [comment]
> I am just wondering if this should on our public docs instead. What do you think @orndorffgrant @renanrodrigo @CalvoM ?

We don't currently have anything in the public docs about users even having the option to permanently detach (iirc), so if we want to make it public-facing it'll need a bit more info/context. What we could do is put this in the devdocs as is for now, and then if we start getting queries about how to permanently detach, we could move it to somewhere public-facing? 

My main question (apologies if it's a stupid one): is this something we expect users will want to do? If so, should it be implemented as a feature rather than a workaround (and then we document the feature)?

**Comment by aciba90** [comment]
> > I am just wondering if this should on our public docs instead. What do you think @orndorffgrant @renanrodrigo @CalvoM ?
> 
> We don't currently have anything in the public docs about users even having the option to permanently detach (iirc), so if we want to make it public-facing it'll need a bit more info/context. What we could do is put this in the devdocs as is for now, and then if we start getting queries about how to permanently detach, we could move it to somewhere public-facing?

I like that approach.

> My main question (apologies if it's a stupid one): is this something we expect users will want to do? If so, should it be implemented as a feature rather than a workaround (and then we document the feature)?

To detach Ubuntu Pro instances is discouraged, and we did not find any valid use case for apart from testing. That's why we have decided to only document it, and if a use case arises then we will implement it as a feature.

**Comment by s-makin** [comment]
> To detach Ubuntu Pro instances is discouraged, and we did not find any valid use case for apart from testing. That's why we have decided to only document it, and if a use case arises then we will implement it as a feature.

That makes sense - given that context, I think if we put this workaround in the public-facing docs, we'd need to think carefully about what message that sends (i.e. that we somehow endorse/encourage doing permanent detaches). If we *did* put it in the public docs, I think it should come with an advisory note to warn against doing it (and what the consequences are if you *do* do it, so that anyone who tries does so from an informed position).

**Review by s-makin — APPROVED** [review]

**Pull request merged**
