### PR TITLE
Create config to add extra params to security url

### PR DESCRIPTION
**Pull request by lucasmoura**
## Proposed Commit Message
Create config to add extra params to security url

We are now creating a feature config that will allow users to pass extra params to the security url we are using on ua fix

## Test Steps
Run the modified unit tests on this PR

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
I think we need to do this differently by updating the query_params that we pass into request_url, not adding a suffix on base_url. Othwerwise, calls we emit which might contain query_params in the future will break if extra_security override is set.

**Comment by lucasmoura** [comment]
@blackboxsw You are totally right on this. I completely missed the infrastructure we already have for query params. Thanks you for spotting that. I have update the code to address that

**Review by blackboxsw — APPROVED** [review]
Validated works as intended.

**Comment by blackboxsw** [comment]
CI failures were run on a node during which it was under investigation for LXC issues. Failures were indicative of lxc init errors.

**Pull request merged**
