### PR TITLE
Drop trusty tests

### PR DESCRIPTION
**Pull request by lucasmoura**
## Proposed Commit Message
tests: drop trusty tests

Drop trusty integration tests and add tests for hirsute and groovy

## Test Steps
Run the modified integration tests

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by blackboxsw — APPROVED** [review]
LGTM. Running these tests now to confirm.

**Review by blackboxsw — CHANGES_REQUESTED** [review]
LGTM. Let's also separately work with @paride to fix the Jenkins jobs to drop automated trusty runs on UAClient as well.


I think we need to sort the expected help tests for hirsute and groovy
  features/attached_commands.feature:366  Help command on an attached machine -- @1.4 ubuntu release
  features/attached_commands.feature:397  Purge package after attaching it to a machine -- @1.4 ubuntu release
  features/attached_enable.feature:160  Attached enable not entitled service in a ubuntu machine -- @1.5 not entitled services
  features/unattached_commands.feature:197  Help command on an unattached machine -- @1.5 ubuntu release

**Comment by lucasmoura** [comment]
@blackboxsw code updated

**Comment by paride** [comment]
@blackboxsw can we just drop all the trusty jobs from Jenkins, or should we keep something?

**Review by blackboxsw — APPROVED** [review]
LGTM. Thanks for the fix, ran both for Groovy and Hirsute and adding it to SRU bug

**Pull request merged**
