### PR TITLE
more datetime json decoding

### PR DESCRIPTION
**Pull request by orndorffgrant**
machine-token: avoid extra json parsing step by recognizing datetime fields
* uses DatetimeDataValue in PublicMachineToken data object to avoid an extra json.loads (DatetimeDataValue didn't exist at the time that was written)

data_types: fix error classes to be proper UserFacingErrors
* while fixing test cases from these changes, I found out that IncorrectFieldType errors fail during our main_error_handler function because they don't have msg_code or additional_info defined.
* This commit is the simplest fix to this - maybe not the best. I want a common IncorrectTypeError that all the more specific errors inherit from, and can't find a better way to make the constructors call super nicely. LMK what you think

util: always parse datetimes in readurl
* uses JsonDatetimeAwareDecoder in util.readurl so we can always be sure datetimes are decoded later on.
* This removes the need for a few other instances of `parse_rfc3339_date`

## Test Steps

Everything should still work

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

## Does this PR require extra reviews?

 - [ ] Yes
 - [x] No

### CODE REVIEW

**Comment by orndorffgrant** [comment]
fixing unit tests...

**Comment by orndorffgrant** [comment]
This is less urgent than I thought it was. I'm setting this aside for now and will come back to it later.

**Comment by lucasmoura** [comment]
@orndorffgrant I think we just need to make that change on postinst as well, since we have a `write` call there as well

**Comment by orndorffgrant** [comment]
@lucasmoura thanks for pointing that out! just fixed and pushed, hopefully that will make CI happy

**Review by renanrodrigo — APPROVED** [review]

**Pull request merged**
