### PR TITLE
Add missing punctuation

### PR DESCRIPTION
**Pull request by lucasmoura**
## Proposed Commit Message
Add missing punctuation

Some FIPS related messages were missing the "." stop punctuation

## Test Steps

Run these integration tests:
```
Attached enable fips on a machine with livepatch active
Attached enable livepatch on a machine with fips active
Attached enable fips on a machine with fips-updates active
```

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Review by blackboxsw — CHANGES_REQUESTED** [review]
I think we also need features changes too for those text stops right?
```bash
fgrep -r "Cannot enable FIPS" features/
features/attached_enable.feature.orig:            Cannot enable FIPS when Livepatch is enabled
features/attached_enable.feature.orig:            Cannot enable FIPS when FIPS Updates is enabled
features/attached_enable.feature:            Cannot enable FIPS when Livepatch is enabled.
features/attached_enable.feature:            Cannot enable FIPS when FIPS Updates is enabled.
```

**Comment by lucasmoura** [comment]
@blackboxsw The integration tests are already correct, meaning that they are expecting the "." punctuation. The issue is that I forgot to update those messages in the code :facepalm:

**Review by blackboxsw — APPROVED** [review]
+1. I was looking at stale BDD feature files this changeset (and black style fix) are good.

**Comment by blackboxsw** [comment]
Unrelated CI failure EOFerror on unable to read ssh banner exhausting retries.
```
      paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

**Pull request merged**
