### PR TITLE
enable: show deduplicated list of supported arches

### PR DESCRIPTION
**Pull request by orndorffgrant**
Fixes: #917

## Test Steps

Run `pro enable` in a way that causes the arch affordance check to fail. Ensure that a de-duplicated list of arches is printed.

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by CalvoM** [comment]
Just a quick question @orndorffgrant, why do we have only two esm-supported arches in [postinst](https://github.com/canonical/ubuntu-advantage-client/blob/225499706b7f73d262dfb1609ecff5ee4094c2b6/debian/ubuntu-advantage-tools.postinst#L48) while in the [docs](https://github.com/canonical/ubuntu-advantage-client/blob/main/docs/references/support_matrix.md) we have more?

**Comment by orndorffgrant** [comment]
Good question @CalvoM! The variable in postinst you're referencing is the list of architectures supported by ESM. The docs you're referencing are the architectures supported by the Pro Client. The Pro Client supports more architectures than ESM because it also delivers other products that support more architectures than ESM does.

**Review by lucasmoura — COMMENTED** [review]
@orndorffgrant this would work for sure, but couldn't we change the contract definitions to only return the expected arches, the ones returned by `dpkg --print-architecture` for the `affordances` instead ?

**Comment by orndorffgrant** [comment]
@lucasmoura we could! But I think it is correct for the server to understand the aliases for different architectures. IMO showing a de-duplicated set is a UI concern that is best handled by the client.

I believe the decision was originally made because of older clients that were still sending the other names. I'm not sure if that specifically applies anymore, but there is at least one other client to the API: the website for /pro. And there could be more clients to the API in the future. Those clients may need to use "x86_64" for some reason, so I think it is good that the API supports it.

**Comment by lucasmoura** [comment]
@orndorffgrant Fair enough, good point

**Review by lucasmoura — APPROVED** [review]

**Pull request merged**
