### PR TITLE
CI: skip integration testing if secrets are missing (SC-911)

### PR DESCRIPTION
**Pull request by paride**
## Proposed Commit Message

```
CI: skip integration testing if secrets are missing

Inspired by [1] but implemented with a reusable workflow.

[1] https://github.com/actions/runner/issues/520#issuecomment-907427748=
```

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by paride** [comment]
Our previous approach didn't work as apparently when doing
```
if: ${{ github.repository == 'canonical/ubuntu-advantage-client' }}
```
in PRs `github.repository` is the *target* repository, even if the workflow runs in the source repository context.

Here I implemented a more proper check using a reusable workflow, a relatively new GH actions feature [1].

[1] https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/

**Comment by paride** [comment]
Test PR that shows that the integration testing is skipped when opening a PR from a fork, without ugly failures: https://github.com/canonical/ubuntu-advantage-client/pull/2036

**Review by renanrodrigo — APPROVED** [review]
Seems to be working good, +1 from my side

**Comment by paride** [comment]
We're all green here, merging!

**Pull request merged**
