### PR TITLE
tests: add jammy integration tests (SC-663)

### PR DESCRIPTION
**Pull request by lucasmoura**
## Proposed Commit Message
tests: add jammy integration tests

Add some integration tests for 22.04 (jammy)

## Test Steps
Run the new integration tests

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [x] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by renanrodrigo** [comment]
Could you include it in `tools/run-integration-tests.py` as well?
Adding it to the constants in the start should do

**Comment by lucasmoura** [comment]
@renanrodrigo updated

**Review by renanrodrigo — APPROVED** [review]
lgtm

**Review by orndorffgrant — APPROVED** [review]
These changes look good to me!

While we're here though. Should we run any VM tests on jammy? Also do any of the clouds have jammy images yet?

**Comment by lucasmoura** [comment]
@orndorffgrant The problem of adding those tests is that we don't have any services that are applicable on jammy, which limits a lot of what we test on vms and clouds. But if you think there is a scenario we can use for testing, just let me know.

And regarding the jenkins part, I don't know if we should add it just yet. I think once we can enable at least one service there, it would be a good call

**Comment by orndorffgrant** [comment]
@lucasmoura good points! Let's merge as is then

**Comment by lucasmoura** [comment]
CI error is unrelated with this change

**Pull request merged**
