### PR TITLE
Remove fips package override logic

### PR DESCRIPTION
**Pull request by lucasmoura**
## Proposed Commit Message

Verify that we don't need the package override logic we perform for fips with the latest changes we have on the staging environment of the contract server

## Test Steps
Run the modified tests and see they still work as expected

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by orndorffgrant** [comment]
I've run several tests and I'm happy with (1) moving the staging contract to production now and (2) removing the hardcoded fips package overrides in next release.

**Comment by renanrodrigo** [comment]
@lucasmoura is this PR still needed? what is the status of the overrides in prod?

**Comment by lucasmoura** [comment]
@renanrodrigo updated

**Review by orndorffgrant — APPROVED** [review]

**Review by renanrodrigo — APPROVED** [review]
very nice step forward, I am merging this too

**Pull request merged**
