### PR TITLE
ubuntu-bug integration

### PR DESCRIPTION
**Pull request by orndorffgrant**
# Test Steps

Submit a bug and make sure the tar file is uploaded properly. See https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1979084 as an example.

```
APPORT_DISABLE_DISTRO_CHECK=1 ubuntu-bug ubuntu-advantage-tools
```

Also just run that on every supported series to make sure the logs are collected successfully, but no need to actually create a bug for each series.

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by CalvoM** [comment]
Submitted the bug https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1979184 and I see it works.

**Review by CalvoM — APPROVED** [review]
LGTM.
Submitted the bug https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1979184 and I see it works.

**Review by renanrodrigo — APPROVED** [review]
Nice, and also nice removal of the root lock
lgtm

**Comment by orndorffgrant** [comment]
Those are excellent points! Thanks for taking a look @murraybd I'll make those changes

**Comment by orndorffgrant** [comment]
@CalvoM @renanrodrigo I just rebased this and fixed conflicts. Please re-review when you have a chance

**Review by CalvoM — APPROVED** [review]
LGTM. The bug info is private.

**Review by renanrodrigo — APPROVED** [review]

**Pull request merged**
