### PR TITLE
Use pycloudlib.toml gce.credentials_path (SC-987)

### PR DESCRIPTION
**Pull request by paride**
## Proposed Commit Message

```
Use pycloudlib.toml gce.credentials_path

Have pycloudlib handle the GCE credentials rather than using
the special GOOGLE_APPLICATION_CREDENTIALS, which is handled
directly by the gcloud library.
```

## Test Steps

Let CI run.

## Desired commit type

 - [x] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by paride** [comment]
This is expected to fail as it requires an update in `pycloudlib.toml`. @blackboxsw can you please update it in the usual way? Then we can retrigger and hopefully GCE integration will pass.

**Comment by paride** [comment]
The awspro failure looks unrelated, I'm a bit surprised by it. I'll try to retrigger the failed jobs (gcppro will fail again - expected for now).

**Comment by orndorffgrant** [comment]
Hi @paride I noticed a small clue that may help here.

When running the test with my personal pycloudlib.toml the test passes.
When running with the shared pycloudlib.toml it times out.

The differences I see are the different credentials, and the shared toml sets the ec2 key-pair settings, which mine does not.

However, the test still times out for me after commenting the ec2 key-pair settings in the shared toml file, which makes me think it could actually be related to the account.

My best guess is that the instances are being launched, but something is preventing us from connecting to them. Is there a new default security group for the account that is blocking ssh maybe (or something like that)?

**Comment by paride** [comment]
Thanks @orndorffgrant, very relevant findings. I'm trying to figure out if anything changed on the keys or security group used in CI.

**Review by orndorffgrant — APPROVED** [review]
Thanks for this!

**Pull request merged**
