### PR TITLE
Packaging: lintian fixes and partial refactor

### PR DESCRIPTION
**Pull request by paride**
## Proposed Commit Message

```
Fix lintian warnings/error and partial refactor

Changes:
  d/ubuntu-advantage-tools.templates: suggest the use of apt                          
  d/control: add Rules-Requires-Root: no                                              
  d/control: bump Standards-Version to 4.5.1, no changes needed                       
  d/lintian-overrides: override maintainer-script-calls-service                       
  d/lintian-overrides: package-supports-alternative-init-but-no-init.d-script                 
  d/control: make ubuntu-advantage-pro Architecture: all                              
  d/*: prefix all the debhelper conf files with the package name                      
  d/u-a-t.postinst move the u-a-pro note to a config script                           
```
## Test Steps

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [x] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

I don't think these apply to the packaging:
 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

### CODE REVIEW

**Comment by paride** [comment]
I split all the changes in separate commits with a short rationale in the commit message.

I think I spotted a couple of other issues with the packaging, but they can't be fixed by changing only stuff in `debian/*`, so I left them out from this PR.

**Review by lucasmoura — APPROVED** [review]

**Comment by lucasmoura** [comment]
Thanks for the help with those package warning @paride

**Comment by blackboxsw** [comment]
CI failure unrelated network timeout:  
```bash      Error executing command: ua fix USN-4539-1
      stdout: 
      stderr: Failed to connect to authentication server
  Check your Internet connection and try again
```

**Review by blackboxsw — APPROVED** [review]
Really excellent. thanks @paride for breaking down the commits and providing more context on these fixes.
Ran through package builds and upgrades to validate behavior on binaries generated

**Pull request merged**
